version 16.11.2022
PapaG2015/java-explore-with-me pull request #2
Opened 2022-11-15 19:35 UTC by PapaG2015

2022-11-25 04:29 UTC, eugene-lenkevich requested changes
Привет, Марат, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

В целом все гут, все на своем месте, явных огрехов точно нет 

Далее, 
наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут вопросы, задавай в слаке, не стесняйся, немножко допилить осталось 

В первую очередь лучше потереть закоментированный код, мелочь, но в глаза бросается, усилий надо не много а эффект сразу на лицо :)

Удачи!

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/ErrorHandler.java
> +    /*
Закоментированный код лучш не оставлять. Его потом трудно будет обратно приделать потому что, скорее всего, все вокруг поменяется, а для истории есть git :)

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/client/StatGetClient.java
> +    public StatGetClient(@Value("${stat-server.url}") String serverUrl, RestTemplateBuilder builder) {
Вот тут есть моментик, который можно улучшить :)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)


Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)


https://www.baeldung.com/spring-profiles

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/compilation/CompilationMapper.java
> +    //@Autowired
И еще в нескольких местах закоментированные куски кода бы почикать :)

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/compilation/CompilationMapper.java
> +                            List<ViewStats> viewStats = statGetClient.getEndPoint(start, end, List.of(url + event.getId()));
Вот тут мне кажется спорный момент так как нарушается принцип единственной ответственности
Задача класса-маппера - перекладывать записи из одного объекта в другой, а тут уже происходит вызов вэб-клиента, к тому же еще и он передается через параметр, как минимум можно было его инжектитть как и другие бины.
А не лучше ли вызов клиента осуществлять в соответствующем методе сервиса, дергающего это преобразование? :)

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/compilation/CompilationService.java
> +    public CompilationService(CompilationRepository compilationRepository,
Можно не задавать руками конструктор, можно добавить аннотацию lombok @RequiredArgsConstroctor

Единственное, поля должны быть final

private final CompilationRepository compilationRepository;
private final EventRepository eventRepository;

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/controllers/admin/events/EventAdminController.java
> +                                             @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeEnd,
@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")

Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/controllers/events/EventPublicController.java
> +        EndPoint endPoint = EndPoint
По своей сути контроллер только обрабатывает (маршрутизирует сервисам) запросы, а тут же в контроллере выполняется некоторая бизнес-логика, ее лучше перенести в сервис, иначе логика размазывается по нескольким классам :)

Плюс аналогичное в других методах)

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/event/model/EventState.java
> +                        EventState.from(s).orElseThrow(() -> new IllegalArgumentException("Unknown state: UNSUPPORTED_STATUS"));
-> new IllegalArgumentException("Unknown state: "+ s))

А не лучше ли тут выводить то что не удалось распарсить, иначе получается не очень очевидно :)

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/event/model/Location.java
> +    private Float lon;
private float lat;
    private float lon;

А не лучше ли тут использовать примитивные типы, обертки Float могут быть null, вроде как, в контексте текущей задачи, от такого объекта нет смысла, что думаешь? :)

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/user/UserRepository.java
> +    List<User> getUsersAtIds(@Param("ids") Set<Long> ids);
Вроде как моно не писать руками тут запрос, попробуй вот такое

List<User> findById( Set<Long> ids);

2022-11-25 04:29 UTC, eugene-lenkevich commented on ewm-main-service/src/main/resources/schema.sql
> +    email varchar,
Имя и почта безразмерные получились, это нормально для поля коментрий или описание, а тут давай, все таки, поэкономим место под БД и какие то ограничения на размер колонки поставим, например так
    name varchar(250),
    email varchar(250),

2022-11-27 07:59 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/ErrorHandler.java
> +    /*
Исправлено, но мелкие комментарии оставил

2022-11-27 08:03 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/compilation/CompilationMapper.java
> +    //@Autowired
Исправлено

2022-11-27 09:05 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/client/StatGetClient.java
> +    public StatGetClient(@Value("${stat-server.url}") String serverUrl, RestTemplateBuilder builder) {
Исправлено

2022-11-27 09:06 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/compilation/CompilationMapper.java
> +    //@Autowired
Исправлено

2022-11-27 11:11 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/compilation/CompilationService.java
> +    public CompilationService(CompilationRepository compilationRepository,
Исправлено

2022-11-27 11:36 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/controllers/events/EventPublicController.java
> +        EndPoint endPoint = EndPoint
Исправлено

2022-11-27 11:40 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/event/model/EventState.java
> +                        EventState.from(s).orElseThrow(() -> new IllegalArgumentException("Unknown state: UNSUPPORTED_STATUS"));
Исправлено

2022-11-27 11:44 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/event/model/Location.java
> +    private Float lon;
Исправил. Я в начале обучения везде пытался писать на примитивах, но в конце перешел на обертки. Мне кажется, что с обертками проще.

2022-11-27 12:04 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/user/UserRepository.java
> +    List<User> getUsersAtIds(@Param("ids") Set<Long> ids);
Есть findAllBy

2022-11-27 16:02 UTC, PapaG2015 commented on ewm-main-service/src/main/resources/schema.sql
> +    email varchar,
Исправлено

2022-11-27 16:21 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/compilation/CompilationMapper.java
> +                            List<ViewStats> viewStats = statGetClient.getEndPoint(start, end, List.of(url + event.getId()));
Исправлено

2022-11-28 06:07 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/event/model/Location.java
> +    private Float lon;
Ну, проще вряд ли будет, компилятор делает многое за счет чего разница минимальна :)

https://habr.com/ru/post/329498/

Но, вообще, суть оберток в том, что они делают эти примитивные типы объектами, что дает возмодность использовать их для типизации в дженериках и, наверное самое главное, такие переменные могут быть null, примитивные же типы нуллом быть не могут. То есть они привносят семантику объектов для наших простых типов

И еще не надо забывать что обертка - это небольшой объект, который потом должен быть очищен сборщиком мусора в то время как примитиные типы создаются в стэке. да и памяти обертка гораздо больше занимает  :)

2022-11-28 06:07 UTC, eugene-lenkevich commented on ewm-main-service/src/main/java/ru/explorewithme/user/UserRepository.java
> +    List<User> getUsersAtIds(@Param("ids") Set<Long> ids);
Отлично

2022-11-28 06:11 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

2022-11-28 16:45 UTC, merged

2022-12-02 06:44 UTC, PapaG2015 commented on ewm-main-service/src/main/java/ru/explorewithme/controllers/admin/events/EventAdminController.java
> +                                             @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime rangeEnd,
Исправил, в тот раз забыл